"""
Django settings for pyvcloud_project project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'jq$)n%@-bmh7#gtsas40dmv-@ghq4z(8nzi&x@s@)=2oyuwr2o'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

AUTHENTICATION_BACKENDS = (
    'pyvcloud_project.ldap_backend.LDAPBackend',
    'django.contrib.auth.backends.ModelBackend',
)

# Application definition
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

ALLOWED_HOSTS = [
    'atpoda1-spp-centos.athtem.eei.ericsson.se',   # Hostname for the VM
    '10.150.173.150',                     # IP address
    '127.0.0.1',                          # Localhost
]

CSRF_TRUSTED_ORIGINS = [
    'https://atpoda1-spp-centos.athtem.eei.ericsson.se',  # Trusted origin for CSRF
]

INSTALLED_APPS = [
    'django_crontab',
    'jet.dashboard',
    'jet',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pyvcloud_project',
    'VMs.apps.VmsConfig',
    'Vapps.apps.VappsConfig',
    'django_rq',
    'django.contrib.admindocs',
    'rest_framework',
    'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

INTERNAL_IPS = [
    '127.0.0.1',
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.history.HistoryPanel',
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
    'debug_toolbar.panels.profiling.ProfilingPanel',
]

JET_THEMES = [
    {
        'theme': 'default',  # theme folder name
        'color': '#47bac1',  # color of the theme's button in user menu
        'title': 'Default'  # theme title
    },
    {
        'theme': 'green',
        'color': '#44b78b',
        'title': 'Green'
    },
    {
        'theme': 'light-green',
        'color': '#2faa60',
        'title': 'Light Green'
    },
    {
        'theme': 'light-violet',
        'color': '#a464c4',
        'title': 'Light Violet'
    },
    {
        'theme': 'light-blue',
        'color': '#5EADDE',
        'title': 'Light Blue'
    },
    {
        'theme': 'light-gray',
        'color': '#222',
        'title': 'Light Gray'
    }
]


# # From Django 3.0 the default value of the X_FRAME_OPTIONS setting was changed from SAMEORIGIN to DENY.
# # This can cause errors for popups such as for the Field Lookup Popup.
X_FRAME_OPTIONS = 'SAMEORIGIN'

ROOT_URLCONF = 'pyvcloud_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR + '/pyvcloud_project/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'pyvcloud_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
# https://docs.djangoproject.com/en/3.0/ref/settings/#std:setting-DATABASES

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'pyvcloud_db'),
        'USER': 'admin',
        'PASSWORD': 'pyvcloudshroot12',
        'HOST': 'localhost',
        'PORT': '',
        'TEST': {
            'NAME': os.path.join(BASE_DIR, 'pyvcloud_test_database'),
        }
    }
}

# Initalized database Test paramater to false
TEST = False
CI_PORTAL_URL = "https://ci-portal.seli.wh.rnd.internal.ericsson.com/"
SPP_URL = "https://atpoda1-spp-centos.athtem.eei.ericsson.se/"

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "pyvcloud_project/static/")

CACHES = {
    'default': {
        'BACKEND': 'redis_cache.RedisCache',
        'LOCATION': 'localhost:6379',
        'OPTIONS': {
            'TIMEOUT': 900,  # 15 min
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'CONNECTION_POOL_CLASS': 'redis.BlockingConnectionPool',
            'CONNECTION_POOL_CLASS_KWARGS': {
                'max_connections': 10,
                'timeout': 20,
            }
        },
    },
}
RQ_QUEUES = {
    'default': {
        'USE_REDIS_CACHE': 'default',
    },
    'high': {
        'USE_REDIS_CACHE': 'default',
    },
    'low': {
        'USE_REDIS_CACHE': 'default',
    },
}
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"
DJANGO_SETTINGS_MODULE = "settings rq worker high default low"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'pyvcloud_log_format': {
            'format': '%(asctime)s [ %(name)s: %(funcName)s: %(lineno)s] [%(levelname)s]: %(message)s',
            'datefmt': "%Y-%m-%d %H:%M:%S"
        }
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': '/var/log/pyvcloud/pyvcloud_portal.log',
            'when': 'W6',  # for weekly log file rotation (w0=Monday)
            'backupCount': 54,  # how many backup log files to keep, 20 weeks
            'formatter': 'pyvcloud_log_format'
        },
        'console': {
            'class': 'logging.StreamHandler',
            'level': 'DEBUG',
            'formatter': 'pyvcloud_log_format'
        },
    },
    'loggers': {
        'console_log': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': True,
        },
        'pyvcloud_project': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'Vapps': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        },
        'VMs': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': True,
        }
    }
}

CRONJOBS = [
    ('0 1 * * *', 'django.core.management.call_command', ['import_database']),
    ('0 2 * * *', 'pyvcloud_project.historical_report_cron_jobs.DatacenterReportDownloadCronJob'),
    ('0 2 * * *', 'pyvcloud_project.historical_report_cron_jobs.VappReportDownloadCronJob'),
]