# Generated by Django 3.1.2 on 2022-10-25 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Citags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.CharField(blank=True, max_length=60, null=True)),
            ],
            options={
                'verbose_name_plural': 'Citags',
            },
        ),
        migrations.CreateModel(
            name='EventTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Event types',
            },
        ),
        migrations.CreateModel(
            name='MigCountTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('graphable_name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name_plural': 'Mig count types',
            },
        ),
        migrations.CreateModel(
            name='MigRas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Mig ras',
            },
        ),
        migrations.CreateModel(
            name='MigTeams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('mig_ra_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.migras')),
            ],
            options={
                'verbose_name_plural': 'Mig teams',
            },
        ),
        migrations.CreateModel(
            name='Orgs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('vcd_id', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('href', models.CharField(blank=True, max_length=300, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name_plural': 'Orgs',
            },
        ),
        migrations.CreateModel(
            name='OrgVdcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('org_vdc_id', models.CharField(max_length=60, null=True)),
                ('running_tb_limit', models.IntegerField(default=0)),
                ('stored_tb_limit', models.IntegerField(default=0)),
                ('vcenter', models.CharField(blank=True, max_length=40, null=True)),
                ('cpu_limit', models.IntegerField(default=0)),
                ('memory_limit', models.IntegerField(default=0)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('mig_ra_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.migras')),
            ],
            options={
                'verbose_name_plural': 'Org VDCs',
            },
        ),
        migrations.CreateModel(
            name='ProviderVdcs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('vdc_id', models.CharField(max_length=60)),
                ('description', models.TextField(blank=True, null=True)),
                ('new_quota_system', models.BooleanField()),
                ('cpu_multiplier', models.DecimalField(decimal_places=5, default=1, max_digits=10)),
                ('memory_multiplier', models.DecimalField(decimal_places=5, default=1, max_digits=10)),
                ('available_cpus', models.IntegerField()),
                ('available_memory_gb', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Provider VDCs',
            },
        ),
        migrations.CreateModel(
            name='SoftwareBuilds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Software builds',
            },
        ),
        migrations.CreateModel(
            name='SoftwareLsvs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Software Lsvs',
            },
        ),
        migrations.CreateModel(
            name='SoftwareReleases',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Software releases',
            },
        ),
        migrations.CreateModel(
            name='SoftwareTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'Software types',
            },
        ),
        migrations.CreateModel(
            name='SppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_groups', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='States',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'verbose_name_plural': 'States',
            },
        ),
        migrations.CreateModel(
            name='TaskTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=128)),
                ('resource_points', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Task types',
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('org_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.orgs')),
            ],
            options={
                'verbose_name_plural': 'Teams',
            },
        ),
        migrations.CreateModel(
            name='ThrottlerSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('value', models.IntegerField()),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'Throttler settings',
            },
        ),
        migrations.CreateModel(
            name='Vapps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcd_id', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('vts_name', models.CharField(blank=True, max_length=45, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=45, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_by_id', models.IntegerField(blank=True, null=True)),
                ('deployed_from_id', models.CharField(blank=True, max_length=60, null=True)),
                ('shared', models.BooleanField(null=True)),
                ('citag_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.citags')),
                ('created_by_user_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.sppuser')),
                ('org_vdc_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.orgvdcs')),
                ('software_lsv_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.softwarelsvs')),
                ('software_release_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.softwarereleases')),
                ('software_type_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.softwaretypes')),
                ('team_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.teams')),
            ],
            options={
                'verbose_name_plural': 'Vapps',
            },
        ),
        migrations.CreateModel(
            name='Vms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcd_id', models.CharField(max_length=60)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('os_family', models.CharField(blank=True, max_length=45, null=True)),
                ('os_name', models.CharField(blank=True, max_length=45, null=True)),
                ('vmware_tools', models.CharField(blank=True, max_length=45, null=True)),
                ('vsphere_name', models.CharField(blank=True, max_length=45, null=True)),
                ('host_name', models.CharField(blank=True, max_length=45, null=True)),
                ('datastore', models.CharField(blank=True, max_length=45, null=True)),
                ('cpu', models.IntegerField(blank=True, null=True)),
                ('memory', models.IntegerField(blank=True, null=True)),
                ('memory_metric', models.CharField(blank=True, max_length=45, null=True)),
                ('storage', models.IntegerField(blank=True, null=True)),
                ('state_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.states')),
                ('vapp_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.vapps')),
            ],
            options={
                'verbose_name_plural': 'VMS',
            },
        ),
        migrations.CreateModel(
            name='VappCitags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.CharField(blank=True, max_length=60, null=True)),
                ('citag_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.citags')),
                ('vapp_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.vapps')),
            ],
            options={
                'verbose_name_plural': 'Vapp citags',
            },
        ),
        migrations.AddField(
            model_name='softwarereleases',
            name='software_type_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.softwaretypes'),
        ),
        migrations.AddField(
            model_name='orgvdcs',
            name='provider_vdc_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyvcloud_project.providervdcs'),
        ),
        migrations.CreateModel(
            name='MigVsphereMappings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcenter_hostname', models.CharField(max_length=128)),
                ('cluster_name', models.CharField(max_length=128)),
                ('mig_team_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.migteams')),
            ],
            options={
                'verbose_name_plural': 'Mig vsphere mappings',
            },
        ),
        migrations.CreateModel(
            name='MigVcloudMappings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spp_hostname', models.CharField(max_length=128)),
                ('mig_team_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.migteams')),
                ('orgvdc_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.orgvdcs')),
            ],
            options={
                'verbose_name_plural': 'Mig vcldoud mappings',
            },
        ),
        migrations.CreateModel(
            name='MigNightlyCounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('count', models.IntegerField()),
                ('mig_count_type_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.migcounttypes')),
                ('mig_team_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.migteams')),
            ],
            options={
                'verbose_name_plural': 'Mig nightly counts',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_dn', models.CharField(max_length=200)),
                ('group_members', models.TextField(blank=True, null=True)),
                ('read_permission', models.BooleanField(default=0, null=True)),
                ('write_permission', models.BooleanField(default=0, null=True)),
                ('admin_permission', models.BooleanField(default=0, null=True)),
                ('group_name', models.CharField(max_length=100)),
                ('restrict_catalogs', models.BooleanField(default=0, null=True)),
                ('unrestricted', models.TextField(blank=True, null=True)),
                ('org_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyvcloud_project.orgs')),
                ('org_vdc_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyvcloud_project.orgvdcs')),
            ],
            options={
                'verbose_name_plural': 'Groups',
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(blank=True, max_length=60, null=True)),
                ('function_name', models.CharField(blank=True, max_length=45, null=True)),
                ('function_parameters', models.TextField(blank=True, null=True)),
                ('value_returned', models.CharField(blank=True, max_length=45, null=True)),
                ('message', models.CharField(blank=True, max_length=500, null=True)),
                ('object_type', models.CharField(blank=True, max_length=45, null=True)),
                ('object_id', models.IntegerField(blank=True, null=True)),
                ('object_vcd_id', models.CharField(blank=True, max_length=45, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('retries', models.IntegerField()),
                ('event_type_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.eventtypes')),
                ('org_vdc_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.orgvdcs')),
            ],
            options={
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AddField(
            model_name='citags',
            name='org_vdc_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.orgvdcs'),
        ),
        migrations.CreateModel(
            name='Catalogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=60, null=True)),
                ('vcd_id', models.CharField(max_length=60)),
                ('user', models.CharField(blank=True, max_length=60, null=True)),
                ('org_obj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.orgs')),
            ],
            options={
                'verbose_name_plural': 'Catalogs',
            },
        ),
    ]
