# Generated by Django 3.1.2 on 2022-12-06 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyvcloud_project', '0002_authdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='vms',
            name='detailed_storage',
            field=models.TextField(blank=True, null=True),
        ),
    ]
