# Generated by Django 3.1.2 on 2022-12-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyvcloud_project', '0002_authdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogs',
            name='allowed_templates',
            field=models.IntegerField(default=1),
        ),
    ]
