# Generated by Django 3.1.2 on 2022-12-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyvcloud_project', '0002_authdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetryInterval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('queue', models.CharField(choices=[('default', 'Default'), ('high', 'High'), ('low', 'Low')], default='default', max_length=100)),
                ('max_retries', models.IntegerField(default=1)),
                ('retry_interval', models.IntegerField(default=1)),
                ('job_timeout', models.IntegerField(default=600)),
            ],
            options={
                'verbose_name_plural': 'RetryIntervals',
            },
        ),
    ]
