# Generated by Django 3.1.2 on 2022-12-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyvcloud_project', '0003_vms_detailed_storage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vms',
            old_name='storage',
            new_name='committed_storage',
        ),
        migrations.AddField(
            model_name='vms',
            name='provisioned_storage',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
