# Generated by Django 3.1.2 on 2022-12-20 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyvcloud_project', '0003_catalogs_allowed_templates'),
        ('pyvcloud_project', '0003_retryinterval'),
    ]

    operations = [
    ]
