# Generated by Django 3.1.2 on 2022-12-06 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyvcloud_project', '0004_auto_20221206_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='vms',
            name='vm_attached_disks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
