# Generated by Django 3.1.2 on 2022-12-20 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyvcloud_project', '0006_merge_20221220_1349'),
        ('pyvcloud_project', '0004_merge_20221220_1223'),
    ]

    operations = [
    ]
