# Generated by Django 3.1.2 on 2023-01-26 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('pyvcloud_project', '0007_merge_20221220_1539'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='object_vcd_id',
            new_name='job_id',
        ),
        migrations.RemoveField(
            model_name='events',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='events',
            name='org_vdc_obj',
        ),
        migrations.RemoveField(
            model_name='events',
            name='value_returned',
        ),
        migrations.AddField(
            model_name='events',
            name='event_stage',
            field=models.CharField(choices=[('Start', 'Start'), ('End', 'End')], default='Start', max_length=45),
        ),
        migrations.AddField(
            model_name='events',
            name='outcome',
            field=models.CharField(blank=True, choices=[('Completed', 'Completed'), ('Failed', 'Failed')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='resource_id',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='event_type_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.eventtypes'),
        ),
        migrations.AlterField(
            model_name='events',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='retries',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='events',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.sppuser'),
        ),
        migrations.AlterField(
            model_name='vms',
            name='vapp_obj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pyvcloud_project.vapps'),
        ),
    ]
