# Generated by Django 3.1.2 on 2023-03-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pyvcloud_project', '0008_auto_20230126_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orgvdcs',
            name='mig_ra_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pyvcloud_project.migras'),
        ),
    ]
