# Generated by Django 4.1.7 on 2023-03-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyvcloud_project', '0010_events_is_api_events_request_hostname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='is_api',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='events',
            name='request_hostname',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
