# Generated by Django 4.1.7 on 2023-03-14 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pyvcloud_project', '0011_events_is_api_events_request_hostname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='request_hostname',
            new_name='request_host',
        ),
    ]
