# Generated by Django 4.1.7 on 2023-03-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyvcloud_project', '0012_rename_request_hostname_events_request_host'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='is_api',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
