# Generated by Django 4.2.1 on 2023-09-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyvcloud_project', '0013_alter_events_is_api'),
    ]

    operations = [
        migrations.AddField(
            model_name='vapps',
            name='origin_catalog_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vapps',
            name='origin_template_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
