# Generated by Django 4.2.1 on 2024-01-22 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyvcloud_project', '0014_vapps_origin_catalog_name_vapps_origin_template_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Historical Reports',
            },
        ),
    ]
